test ks8

diff --git a/jenkins/Dockerfile b/jenkins/Dockerfile
--- a/jenkins/Dockerfile
+++ b/jenkins/Dockerfile
@@ -1,6 +1,9 @@
 # Usamos la imagen Jenkins LTS
 FROM jenkins/jenkins:lts
 
+# # Usamos la imagen de Jenkins como base
+FROM jenkins/jenkins:lts
+
 # Copiamos el binario de Docker desde la imagen docker:dind
 COPY --from=docker:dind /usr/local/bin/docker /usr/local/bin
 
@@ -12,6 +15,12 @@ RUN curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/s
     && chmod +x kubectl \
     && mv kubectl /usr/local/bin/kubectl \
     && echo "kubectl instalado correctamente: $(kubectl version --client --short || echo 'Error en instalación')"
+
+# Instalamos KIND
+RUN curl -Lo ./kind https://github.com/kubernetes-sigs/kind/releases/download/v0.18.0/kind-linux-amd64 \
+    && chmod +x ./kind \
+    && mv ./kind /usr/local/bin/kind \
+    && echo "kind instalado correctamente: $(kind --version || echo 'Error en instalación')"
 
 # Creamos el grupo 'docker' y agregamos al usuario 'jenkins'
 RUN groupadd docker && usermod -aG docker jenkins
